# Generated by Django 3.2.15 on 2023-03-31 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=5,
                        message="Хорошее блюдо за 5 минут не приготовишь!",
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=500, message="Слишком долго! Может лучше заказать?"
                    ),
                ],
                verbose_name="Время приготовления рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="recipeproduct",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Нулевок значение недопустимо!"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=999999,
                        message="Готовишь для большой компании? Слишком много продуктов даже для компании! ",
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
